### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by vmosoti** [spiritix/lada-cache#66]
The above error is thrown when using  [Laravel 5.7 Sub-Query Joins](https://laravel.com/docs/5.7/queries#joins)

```php
$payments = Payment::groupBy('file_id');

    $files = File::join('clients', function ($join) {
        $join->on('clients.id', '=', 'files.client_id')
            ->where('clients.active', 1)
            ->whereNull('deleted_at');
    })->leftJoinSub($payments, 'payments', function ($join) {
        $join->on('files.id', '=', 'payments.file_id');
    })->select('files.*')
        ->addSelect(DB::raw('SUM(payments.amount) as total_paid'))
        ->take(10)
        ->get();

    dump($files);
```
Any way to deal with this?

**Comment by spiritix** [comment]
Fixed the bug in the current version (3.0). Works without exception now.

However, using 'leftJoinSub' might lead to cache misses since Lada Cache isn't able to properly tag such queries. 
The problem is that the provided join query is immediately converted into raw SQL and can therefore not be handled by Lada Cache anymore.
Getting this working would require larger overrides of the Laravel query builder.
If anyone would like to work on that, just uncomment the following assertion: https://github.com/spiritix/lada-cache/blob/master/tests/TaggerTest.php#L272

**Comment by jordanade** [comment]
I'm getting the same error in 3.0.2 with the following code, which worked prior to installing lada-cache:
```
// get sessions per page/site per day
$page_sessions = PageView::from(DB::raw("
	(
		SELECT * FROM page_views
		WHERE
			".($entity_name=='sites'?
				"site_id={$entity->id}"
				: "page_id={$entity->id}"
			)."
			AND server_mode = 'domain'
			AND viewed_at >= '{$report_begin}'
			AND viewed_at <= '{$report_end}'
		ORDER BY viewed_at ASC
	) AS views
"))
	->groupBy("session_id")
	->get()
;
```

**Comment by spiritix** [comment]
Will fix this in a release later today. However, I strongly recommend you to not use raw queries like this, they won't work with Lada Cache and break any abstraction of the database in general.

**Comment by jordanade** [comment]
Thanks! I believe it was written this way because an earlier version of Laravel didn't allow me to use a subquery with a group by or something. Also I don't want to use lada-cache with this table anyways (it's a log table) but excluding it in the config doesn't seem to be effective. I still see 
```
[Invalidation (insert)] insert into `page_views` 
``` 
despite having 
```   
 'exclude-tables' => [
        (new App\PageView())->getTable(),
 ],
``` 
in the config. OK, that's a different issue!

**Comment by spiritix** [comment]
Yes, currently Lada Cache does even invalidate items which have been excluded from caching. This doesn't affect the functionality but is indeed suboptimal. Will improve it in a later version.
